# Generated by Django 3.1.3 on 2020-11-18 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('userid', models.CharField(db_index=True, max_length=20)),
                ('email', models.CharField(db_index=True, max_length=30)),
                ('hp', models.CharField(db_index=True, max_length=11)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-regdate'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(db_index=True, max_length=10)),
                ('wdate', models.DateTimeField(auto_now_add=True)),
                ('ans_stat', models.CharField(db_index=True, max_length=3)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.member')),
            ],
            options={
                'ordering': ['-wdate'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('qdesc', models.CharField(db_index=True, max_length=150)),
                ('answer', models.CharField(db_index=True, max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.faq')),
            ],
        ),
    ]
