# Generated by Django 3.1.3 on 2020-11-19 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='qtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.faq'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.member'),
        ),
    ]
