# Generated by Django 3.1.3 on 2020-11-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20201119_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-wdate'], 'verbose_name': 'faq', 'verbose_name_plural': 'faqs'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-regdate'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
